version: 2.1

jobs:
  build-and-test:
    macos:
      xcode: "15.2.0"
    resource_class: macos.m1

    steps:
      - checkout

      - run:
          name: Build and run tests
          command: |
            xcodebuild test \
              -project GithubAPIWrapper.xcodeproj \
              -scheme GithubAPIWrapper \
              -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest'

workflows:
  ios-ci:
    jobs:
      - build-and-test


